### ISSUE TITLE
流程判断缺少小于等于和大于等于（数据聚合也一样）

### ISSUE THREAD

**Issue by bobandyou** [getrebuild/rebuild#112]
## 版本号
TODO

## 什么问题
TODO

## 如何复现此问题
TODO

## 系统环境（操作系统/浏览器）
TODO

**Comment by devezhao** [comment]
已经有大于小于，可满足多样的查询需求，过多选项会给使用带来不便。

**Comment by bobandyou** [comment]
小于2000元部门经理审核，大于2000元总经理审核，如果正好2000元呢？

**Comment by devezhao** [comment]
你说的有道理，我们会考虑加上。着急的话你也可以自己先加上
