### ISSUE TITLE
1.7.1部署乱码 

### ISSUE THREAD

**Issue by allenlei2010** [getrebuild/rebuild#116]
## 版本号
1.7.1

## 什么问题
乱码

## 如何复现此问题
[https://images.gitee.com/uploads/images/2019/1226/160346_e7e938a2_409461.png](url)

## 系统环境（操作系统/浏览器）
环境window64
tomcat8.0.53
jdk1.8
myeclipse2016
mysql设置的编码为utf-8 utf-8
myeclipse项目工程编码为utf-8
firefox

**Comment by devezhao** [comment]
https://gitee.com/getrebuild/rebuild/issues/I17DGB#note_2172538
