### ISSUE TITLE
一些基本业务难以实现

### ISSUE THREAD

**Issue by bobandyou** [getrebuild/rebuild#117]
## 版本号
TODO
1.7.1
## 什么问题
TODO
1. 创建一个定单，包括采购项目、数量、单价、小计，小计没法自动计算出来，尽管有数据聚合，但是不能选当前实体为目标实体。
2. 客户和订单是一对多关系，在列表模式下，如果在客户表格中显示订单编号，则只能显示和编辑一条记录；在新建相关中可以添加多条记录，但是在列表模式下新增的记录在这里却不显示。
3. 数据聚合不能支持跨实体的数据源。
## 如何复现此问题
TODO

## 系统环境（操作系统/浏览器）
TODO

**Comment by devezhao** [comment]
问题1. 后续考虑支持本实体
问题2. 暂不考虑支持
问题3. 请具体场景举例

**Comment by bobandyou** [comment]
问题3的业务场景：
采购价格（美元）=采购单实体.单价（人民币）*汇率实体.美元汇率

**Comment by bobandyou** [comment]
问题2：
建议把所有一对多、多对多用明细表编辑时主表从表的模式显示，可以有spread和form两种视图。一来可以添加明细条目，二来不需要跳转到明细表才编辑，三来明细表实体这个类别也可以去掉了。

**Comment by devezhao** [comment]
> 问题2：
> 建议把所有一对多、多对多用明细表编辑时主表从表的模式显示，可以有spread和form两种视图。一来可以添加明细条目，二来不需要跳转到明细表才编辑，三来明细表实体这个类别也可以去掉了。

系统目前没有提供多对多字段的支持，只能变相实现，因此你才会遇到问题2。
直接在主表单/视图操作明细，这个在后续的规划中，目前也是一种变相实现，所以使用上不是很方便。

**Comment by devezhao** [comment]
Fixed #125
