### ISSUE TITLE
数据库链接问题

### ISSUE THREAD

**Issue by xnrcms** [getrebuild/rebuild#122]
## 版本号
1.7.2

## 什么问题
为什么我本地故意把数据库链接配置写错，启动程序还可以正常登录和页面操作，这些数据保存到哪里了？我发现我的数据库也没有数据，最重要的是我数据库账号密码写错，甚至我把数据库链接地址和端口改了 也能正常打开后台，真是太诡异了。我以为是启动程序错了，我试着在页面随便输的东西，发现页面有变化，这个程序到底连的哪里的数据库呀？

## 如何复现此问题
修改数据库配置文件，故意写错，依然可以正常登录和操作

## 系统环境（操作系统/浏览器）
window 火狐和谷歌

**Comment by devezhao** [comment]
如果你是开发环境（启动参数加 `-Drbdev=true`，详见 [启动参数](https://getrebuild.com/docs/dev/#%E5%90%AF%E5%8A%A8%E5%8F%82%E6%95%B0)），那么会使用默认的 ` jdbc.properties` 文件配置。
如果你是产品环境（通过安装程序初始化），那么系统会使用 `~/.rebuild/.rebuild` 文件覆盖默认配置。（`~` 表示用户目录）

**Comment by xnrcms** [comment]
谢谢 你的回答，上面的问题解决了！但是线上部署一直要提示安装，我是本地打完包直接放到服务器上，数据库配置我都是配置好的，本地运行好的代码到线上也必须走一遍安装？

**Comment by devezhao** [comment]
不用的，系统通过加载 `~/.rebuild/.rebuild` 文件判断是否安装。也就是说你把这个文件复制放到新机器上即可。

**Comment by xnrcms** [comment]
我在做REBUILD技术评估，给领导演示，我现在部署的Linux环境遇到以下几个问题
1，window下通过maven打包，直接将target下rebuild复制到服务器上？
2，Linux下的tomcat是否要配置启动项Drbdev=true？
3，window下的.rebuild目录也可以直接复制上去？ .rebuild这个目录是否必须要存在？
4，根据你们官方的文档，在部署这块说的也比较少，我在导入数据库时有一张表就遇到索引超限
5，你们系统部署对服务器的配置是否有要求？刚才部署发现启动很慢

**Comment by devezhao** [comment]
1. 是
2. 不需要。仅开发时需要，他决定了系统启动/运行时的一些行为
3. 目录肯定也要正确，不然到哪找这个文件
4. 系统初始脚本在 MySQL5.6 下会有警告，但只是警告，不影响使用
5. 启动时间一般在30秒左右，如果时间比较长，检查下 MySQL、Redis（如有）是否可以被连接
6. 启动失败了就会自动转到错误页，具体原因看错误日志

**Comment by devezhao** [comment]
如果部署有困难，建议下载 standalone 版本使用。

**Comment by xnrcms** [comment]
我们需要二次开发

**Comment by devezhao** [comment]
> 谢谢 你的回答，上面的问题解决了！但是线上部署一直要提示安装，我是本地打完包直接放到服务器上，数据库配置我都是配置好的，本地运行好的代码到线上也必须走一遍安装？

升级和迁移文档 https://getrebuild.com/docs/admin/upgrade
