### ISSUE TITLE
表单布局中的分栏信息在表单录入时没有显示

### ISSUE THREAD

**Issue by zhangsean** [getrebuild/rebuild#128]
## 版本号
v1.7.2

## 什么问题
表单布局中的分栏信息在表单录入时没有显示

## 如何复现此问题
1、在实体表单布局中添加分栏，分栏属性输入信息，比如：人员基本信息、人员特殊信息。
2、添加人员实体菜单后，添加人员，人员信息表单中没有显示分栏，也没有体现出单列和双列的设置，都是单列显示。

## 系统环境（操作系统/浏览器）
MacOS 10.15.3
Chrome 78

**Comment by devezhao** [comment]
此为已知问题，新建/编辑页暂不支持双列和分栏，后续会考虑支持。

**Comment by devezhao** [comment]
新建/编辑页已支持分栏，会在本月的 v1.8 发布，双列暂无计划。
