### ISSUE TITLE
删除目录和数据库后，重装rebuilds时提示错误：Unknown database 'rebuild10'

### ISSUE THREAD

**Issue by liushishi1995** [getrebuild/rebuild#141]
## 版本号
1.7.2和1.8.0（均为一键安装包版本）
## 什么问题
之前已安装版本1.7.2并创建mysql数据库，可正常使用。
但删除安装目录和数据库后，再次重装时出现如下错误：
###################################################################
[INFO  15:28:21,034] <localhost-startStop-1> server.ServerListener#contextInitialized:60 - Rebuild Booting (1.7.2) ...
[INFO  15:28:21,444] <localhost-startStop-1> server.ServerListener#contextInitialized:73 - Initializing Spring context ...
[WARN  15:28:22,244] <localhost-startStop-1> utils.AES#decryptNothrow:103 - Decrypting Error! Use input: vXwBKYUosMpJRO9jeG9+IA==
[WARN  15:28:22,254] <localhost-startStop-1> utils.AES#decryptNothrow:103 - Decrypting Error! Use input: zYkDunIsyaZd71rZoW1KPtJPIutYBsBqNaZxpE+4xNl9urgpG+Py0Q0w5m2+Z72e
[WARN  15:28:22,254] <localhost-startStop-1> utils.AES#decryptNothrow:103 - Decrypting Error! Use input: Ke7e7qzT+5F2HC3C/89a5Aq+UopTPHygiSpPfnQjnSrpxgUtiSlauQbPnowtl+ew
[WARN  15:28:22,254] <localhost-startStop-1> utils.AES#decryptNothrow:103 - Decrypting Error! Use input: vRnLDh4PVen2faMH+itQuFjzwBcWtCTO6qslkF36VAoKxKZT7YVYoWKjP8gPrEIS
[WARN  15:28:22,264] <localhost-startStop-1> utils.AES#decryptNothrow:103 - Decrypting Error! Use input: w07FOXTgIF5vuU2uWOLHhgeBv2dSExddnQQ8f534GXMKxKZT7YVYoWKjP8gPrEIS
[INFO  15:28:23,034] <localhost-startStop-1> server.ServerStatus$Status#<init>:181 - Checking CreateFile : [ OK ]
[ERROR 15:28:23,374] <localhost-startStop-1> server.ServerStatus$Status#<init>:183 - Checking Database : [ ERROR ] Unknown database 'rebuild10'
[WARN  15:28:25,024] <localhost-startStop-1> cache.BaseCacheTemplate#testJedisPool:130 - Acquisition J/Redis failed : Could not get a resource from the pool !!! Using backup ehcache for class com.rebuild.server.helper.cache.CommonCache
[INFO  15:28:25,074] <localhost-startStop-1> server.ServerStatus$Status#<init>:181 - Checking Cache/EHCACHE : [ OK ]
[ERROR 15:28:25,094] <localhost-startStop-1> server.Application#init:124 - 

## 如何复现此问题
使用1.8.0安装也出现上述错误

**Comment by liushishi1995** [comment]
应该是还有数据库的残留信息，导致访问localhost:18080没有直接引导到安装页面，而是错误页面提示找不到数据库。
rebuild-standalone安装目录下的文件皆已全部删除，请核实是否还请有其它残留，谢谢。

**Comment by liushishi1995** [comment]
已核实：如需重装rebuilds，除删除安装目录文件和数据库外，还需清除默认的数据文件夹 ~/.rebuild/（其中 ~ 表示用户目录）。再次重启服务方可正常引导至安装页面。

**Comment by devezhao** [comment]
是的。
也可以直接升级，之前版本的数据系统会自动保证其兼容性。https://getrebuild.com/docs/admin/upgrade
