### ISSUE TITLE
数据聚合的问题

### ISSUE THREAD

**Issue by alexjeo** [getrebuild/rebuild#143]
## 版本号
TODO

## 什么问题

商品库存表 ，商品出库单（主表），商品出库单细表
     怎么能比较的实现确认出库了，自动扣减库存？
    当前都是求和，而数据聚合的时候主子表很好聚合，但是和库存表关联不了。
   请教思路。
## 如何复现此问题
TODO

## 系统环境（操作系统/浏览器）
TODO

**Comment by devezhao** [comment]
> 另外请问，为什么我创建的订单表，没有变成演示系统订单那种风格（带明细标识的），而是依然分成两个表。前端显示时，明细与主表也没有办法关联。

新建（明细）实体的时候，有个【这是一个明细实体】选项。

**Comment by devezhao** [comment]
实现聚合就需要这些实体有关联关系，思考下怎么组织实体结构

**Comment by alexjeo** [comment]
主表和明细表问题修复，当前选择后无法在页面上实现演示系统订单（明细表）的效果。

将
entity-new.jsx将文件中的
  if ($val('#isSlave') == true) {
改为即可，
  if ($val('#isSlave') == 'true') {
或改为
  if ($val('#isSlave')) {
上述两种方法都测试过

这个问题在去年做项目时也遇到过，这个地方有点莫名其妙。
唯一的可能是当 $val('#isSlave') == true用时变为了，'true' == true 为false

仅供大佬参考

**Comment by alexjeo** [comment]
大佬，我也在想着怎么改造实现这些聚合的问题。有思路了，我发出来给您瞧瞧！

> 实现聚合就需要这些实体有关联关系，思考下怎么组织实体结构

我也在思考这个问题，当前正在一边试用，一边摸代码结构，有想法就和找您到请教！

**Comment by devezhao** [comment]
> 主表和明细表问题修复，当前选择后无法在页面上实现演示系统订单（明细表）的效果。
> 
> 将
> entity-new.jsx将文件中的
> if ($val('#isSlave') == true) {
> 改为即可，
> if ($val('#isSlave') == 'true') {
> 或改为
> if ($val('#isSlave')) {
> 上述两种方法都测试过
> 
> 这个问题在去年做项目时也遇到过，这个地方有点莫名其妙。
> 唯一的可能是当 $val('#isSlave') == true用时变为了，'true' == true 为false
> 
> 仅供大佬参考

`if ($val('#isSlave') == 'true')` 可以的，麻烦你推个 PR 到 master，或者等我们后面修复。
