### ISSUE TITLE
install

### ISSUE THREAD

**Issue by 010239** [getrebuild/rebuild#150]
## 版本号
1.8

## 什么问题
安装第一步 出现「连接错误 : Public Key Retrieval is not allowed」

## 系统环境（操作系统/浏览器）
windows10

**Comment by getrebuild** [comment]
是 MySQL8.0 版本？目前我们没有在 8.0 版本下测试过，建议使用 MySQL 5.6/5.7 版本。

**Comment by devezhao** [comment]
MySQL8.0 仅支持 `mysql_native_password` 认证模式。
