### ISSUE TITLE
Installing on Linux

### ISSUE THREAD

**Issue by EL-File4138** [getrebuild/rebuild#170]
### 版本
TODO

### 什么问题 
官方文档似乎没有提供Linux系统的安装方式，是否意味着不官方支持Linux安装呢

### 如何复现此问题
TODO

### 系统环境（操作系统/MySQL版本/浏览器）
TODO

**Comment by devezhao** [comment]
文档可能存在少许误解，实际上我们鼓励使用 Linux/Unix 系统，因为无论在稳定性还是性能都远超 Windows 。每个版本我们都提供了一键安装包，其中内置了 Tomcat 和 JRE（Windows 版本），此安装包同时适用于多个平台（内置的 JRE 则仅适用 Windows，因此需自行准备）。

**Comment by EL-File4138** [comment]
感谢
建议开发团队修改下文档，现在的很有误导性以至于我以为只提供了Windows版本

EL_File4138

________________________________
