### ISSUE TITLE
用户密码不支持特殊字符？

### ISSUE THREAD

**Issue by wangbf19740612** [getrebuild/rebuild#184]
### 版本
1.10.0

### 什么问题 
修改用户密码出错

### 如何复现此问题
密码中包含@等特殊字符提示修改成功，登陆时提示密码不对

### 系统环境（操作系统/MySQL版本/浏览器）
windows mysql5.7

**Comment by devezhao** [comment]
此问题是由于特殊字符在传递到后台进行了 URLEncode 所致。感谢反馈，我们将尽快发布修订版。

**Comment by devezhao** [comment]
已发布修订版 https://github.com/getrebuild/rebuild/releases/tag/1.10.1
