### ISSUE TITLE
安装时增加可选.rebuild文件路径

### ISSUE THREAD

**Issue by wangbf19740612** [getrebuild/rebuild#185]
记得之前某个版本是可以的，现在自动设置到用户目录，能否提供可选项，standalone包，谢谢

**Comment by devezhao** [comment]
在 Tomcat/JVM 启动参数中增加一个自定义参数 `-DDataDirectory=xxx` xxx 即为路径，请自行保证路径正确性

**Comment by devezhao** [comment]
因此，也可以通过指定 `DataDirectory` 参数在一台机器上安装多个 RB 实例。

**Comment by wangbf19740612** [comment]
收到，感谢
