### ISSUE TITLE
功能使用咨询 #2

### ISSUE THREAD

**Issue by aertaa** [getrebuild/rebuild#189]
### 版本
1.10.1

### 什么问题 
团队的各位老师辛苦了，有两个问题想请教：

1. [新增] 元数据获取/业务数据增删改查 API 功能中，以 EntityList 类为例，调用的 apiName 为 "entity/list"，那么请求该 API 的地址为 "/gw/api/entity/list" ，此路径访问报 404 错误，将 apiName 修改为单层目录后正常调用，请问我的理解是否正确？另请问是否第三方系统中需写好与 RB 相同的 sign 方法后，方可使用 API 功能？

2. 目前能否实现某用户使用某实体时带条件查询，或能否提供简单思路？例如，多仓库库存表，表中引用仓库实体，用户与仓库实体为一对多关系，用户只能读取其对应仓库的部分数据。

谢谢。

### 如何复现此问题
TODO

### 系统环境（操作系统/MySQL版本/浏览器）
TODO

**Comment by devezhao** [comment]
1. API 功能当前版本还没有完全对外开放，因此可能存在一些问题
2. 自定义的条件过滤，可以参考 `EntityQueryFilter` 类，他基于角色权限进行过滤，你可以自己实现一个然后查询时自动注入（参考 `QueryFactory` 类）

**Comment by aertaa** [comment]
感谢您的解答，解决了我的疑问。
