### ISSUE TITLE
触发器 - 自动分派 问题咨询

### ISSUE THREAD

**Issue by aertaa** [getrebuild/rebuild#192]
### 版本
1.10.1

### 什么问题 
若对某实体设定一个触发器，执行操作为自动分派，操作内容为按角色平均分派，那么符合角色条件的已停用用户也能够接受分派。用户创建后无法修改部门及角色，并且一旦使用，不能删除只能改为停用。

### 如何复现此问题
TODO

### 系统环境（操作系统/MySQL版本/浏览器）
TODO

**Comment by devezhao** [comment]
1. 停用用户不能接受分派（这个我们需要验证下，若为bug会在修订版修复）
2. 可以修改部分和角色，在客户视图右侧 [更多] 菜单中修改（需要具备管理员角色才能修改）
