### ISSUE TITLE
CSS 样式问题

### ISSUE THREAD

**Issue by aertaa** [getrebuild/rebuild#194]
### 版本
1.10.2

### 什么问题 
手机端预览图片时，根据上传图片长宽比例不同，会导致蒙版样式错位，影响分享、下载、关闭功能使用。
http://klmf-cdn.kalaimanfei.com/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20200716171954.jpg
http://klmf-cdn.kalaimanfei.com/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20200716171959.jpg

两张图片地址如下：
http://klmf-cdn.kalaimanfei.com/rb/20200715/201726650__4d086e061d950a7b6f7a-00d162d9f3d3c9d4.jpg
http://klmf-cdn.kalaimanfei.com/rb/20200715/195922193__98b535e00856e3e0.jpg

### 如何复现此问题
TODO

### 系统环境（操作系统/MySQL版本/浏览器）
TODO

**Comment by devezhao** [comment]
抱歉，RB 目前暂未对手机端进行适配，后续可能也不会，因为 RB 有开发手机端的计划。从操作习惯，页面布局，功能模块等方面，PC 与手机都存在着很大的差异，如果使用 PC 页强制适配手机端，效果会大打折扣。
