### ISSUE TITLE
“无效审批流程”错误

### ISSUE THREAD

**Issue by bingyuxq** [getrebuild/rebuild#204]
### 版本
1.11.0-dev

### 什么问题 
当流程只经过发起人和抄送人2个步骤而未途径审批步骤时会发生“无效审批流程”错误

### 如何复现此问题
流程只配置发起人和抄送人两个步骤，或在分支选择时刻意避开所有审批节点

### 系统环境（操作系统/MySQL版本/浏览器）
nightly demo环境下可复现

**Comment by devezhao** [comment]
审批流程必须有审批节点，否则即为无效。

**Comment by bingyuxq** [comment]
对分支流程场景中，有些分支中可能会不需要审批只做抄送告知一下，诸如费用审批，低于30万可能不需要更高级主管审批但需要抄送通知上级，这种比较普遍的应用场景就无法实现了

**Comment by devezhao** [comment]
明白了，分支的这个我们看一下。另外提供两个建议：
1. 生产环境不建议使用 `dev` 版本，存在不稳定的功能（会有版本兼容问题）
2. 不需要走流程审批的可以使用自动审批功能（v1.11 版本）

**Comment by devezhao** [comment]
验证了下，只要在流转环节中有1个审批节点就不会出现你所述的问题。你真正遇到的问题是“提交即审批（通过）”，这个需求我们需要斟酌一下。

**Comment by bingyuxq** [comment]
当出现如下的流程时最右侧流程将会导致错误发生，这种业务场景还是很常见的

![捕获](https://user-images.githubusercontent.com/11748396/89171113-42838800-d5b3-11ea-8037-e991ad6383d6.PNG)

**Comment by devezhao** [comment]
建议使用 触发器-自动审批
