### ISSUE TITLE
分支判断引用可修改字段时会造成条件判断与修改的逻辑判断倒置

### ISSUE THREAD

**Issue by bingyuxq** [getrebuild/rebuild#208]
版本
1.11.0-dev

什么问题
当分支流程的分支条件在该步骤可编辑时，分支判断时并未使用修改后的值，而是使用了旧的值带入了分支判断。

如何复现此问题
![捕获](https://user-images.githubusercontent.com/11748396/89974011-75550c80-dc94-11ea-9101-f4d0aeb51650.PNG)
目前字段编辑和审批提交放在了同一个交互页面，导致在后端必然先初始化下一步流程实例后才能收到修改后的数据，建议将字段内容编辑从审批提交交互页面拆分成2个独立页面，先完成修改提交再初始化下一级流程实例，或在字段内容发生改变时异步初始化流程下一级实例

系统环境（操作系统/MySQL版本/浏览器）
nightly demo环境下可复现

**Comment by devezhao** [comment]
感谢反馈！这个问题我们验证了一下，目前暂时还没想到好的处理方式（修改与审批分离过去也做过，效果不太好），此问题会持续跟进。
