### ISSUE TITLE
触发器问题咨询

### ISSUE THREAD

**Issue by aertaa** [getrebuild/rebuild#213]
### 版本
1.11.0

### 什么问题 
我对一个实体设定了每小时执行10次的数据聚合触发器，但并不生效。
且服务器开启后每分钟持续报如下 INFO
[INFO  02:16:00,008] <org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-5> helper.DistributedJobBean#isSafe:58 - The job has been executed by another instance : com.rebuild.server.business.trigger.impl.TriggerByTimerJob
[INFO  02:17:00,008] <org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-2> helper.DistributedJobBean#isSafe:58 - The job has been executed by another instance : com.rebuild.server.business.trigger.impl.TriggerByTimerJob
[INFO  02:18:00,008] <org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-4> helper.DistributedJobBean#isSafe:58 - The job has been executed by another instance : com.rebuild.server.business.trigger.impl.TriggerByTimerJob
[INFO  02:19:00,024] <org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-1> helper.DistributedJobBean#isSafe:58 - The job has been executed by another instance : com.rebuild.server.business.trigger.impl.TriggerByTimerJob

请问是什么原因造成的？

### 如何复现此问题
TODO

### 系统环境（操作系统/MySQL版本/浏览器）
TODO

**Comment by getrebuild** [comment]
此为 bug，将在近日发布的 v1.11.1 中修复
