### ISSUE TITLE
启动时控制台报错

### ISSUE THREAD

**Issue by aertaa** [getrebuild/rebuild#226]
### 版本
1.11.1

### 什么问题 
启动时，控制台报如下错误：
[ERROR 14:32:56,651] <localhost-startStop-1> helper.SysConfiguration#getFileOfData:46 - Couldn't mkdirs for data :
之后此 ERROR 多次出现

### 如何复现此问题
TODO

### 系统环境（操作系统/MySQL版本/浏览器）
TODO

**Comment by getrebuild** [comment]
确认数据目录权限可写。默认数据目录为 `~/.rebuild/`

**Comment by aertaa** [comment]
我使用了 Windows Server 2019 Datacenter 操作系统，版本号1809，数据目录路径为：C:\Users\Administrator\.rebuild，此路径确认可写，但仍报上述错误。
出现此错误前，我将 rebuild-standalone\REBUILD 目录中内容由 1.11.0 整体替换为 1.11.1，重新启动 tomcat 后此错误出现。
请问我的操作是否有问题？

**Comment by getrebuild** [comment]
下载下最新版 1.11.2
