### ISSUE TITLE
表单功能请教

### ISSUE THREAD

**Issue by aertaa** [getrebuild/rebuild#231]
### 版本
1.11.2

### 什么问题 
请问团队老师，构建一个实体后，“链接”类型的字段能否增加功能，使得该字段能够使用该实体中的变量，类似“条形码（二维码）”字段的效果？谢谢。

### 如何复现此问题
TODO

### 系统环境（操作系统/MySQL版本/浏览器）
TODO

**Comment by getrebuild** [comment]
无此功能，这可能需要你们自行开发
