### ISSUE TITLE
版本升级咨询

### ISSUE THREAD

**Issue by aertaa** [getrebuild/rebuild#238]
### 版本 / Version
1.11.2

### 什么问题 / What's the problem
请问团队老师，1.11.2 版本升级到 2.0 版本的方法是什么？有什么特别需要注意的地方吗？
感谢回复。

### 如何复现此问题 / How to reproduce this problem
TODO

### 系统环境 (操作系统/MySQL版本/浏览器等) / System environment (OS/MySQL/Browser etc)
TODO

**Comment by devezhao** [comment]
没有需要特别注意的地方，与之前升级一样。可参考此文档 https://getrebuild.com/docs/admin/upgrade#%E7%B3%BB%E7%BB%9F%E5%8D%87%E7%BA%A7
