### ISSUE TITLE
管理员密码修改问题

### ISSUE THREAD

**Issue by advisen** [getrebuild/rebuild#241]
### 版本 / Version
2.0.0

### 什么问题 / What's the problem
管理员密码不能使用特殊字符。

### 如何复现此问题 / How to reproduce this problem
修改管理员密码（包含特殊字符）可以正常登录，但是无法进入后台system配置界面。

### 系统环境 (操作系统/MySQL版本/浏览器等) / System environment (OS/MySQL/Browser etc)
CENTOS 7.6/MYSQL 5.7/

**Comment by getrebuild** [comment]
感谢反馈，我们将于近日发布 2.0.1 修订
