### ISSUE TITLE
第三方服务希望支持自定义

### ISSUE THREAD

**Issue by advisen** [getrebuild/rebuild#242]
### 版本 / Version
2.0.0.

### 什么问题 / What's the problem
第三方服务能支持自定义
比分说短信、邮件支持腾讯、阿里云等短信和邮箱

### 如何复现此问题 / How to reproduce this problem
TODO

### 系统环境 (操作系统/MySQL版本/浏览器等) / System environment (OS/MySQL/Browser etc)
TODO

**Comment by devezhao** [comment]
邮箱可使用 SMTP https://getrebuild.com/docs/admin/integration#%E4%BD%BF%E7%94%A8%20SMTP%20%E9%82%AE%E4%BB%B6
