### ISSUE TITLE
新建立实体搜索的问题

### ISSUE THREAD

**Issue by advisen** [getrebuild/rebuild#247]
### 版本 / Version
2.0.1

### 什么问题 / What's the problem
新建立实体搜索的问题

### 如何复现此问题 / How to reproduce this problem
新建立了一个实体模块，添加数据后，无法快速查询，如下图
![1](https://user-images.githubusercontent.com/40630819/98754153-060cc700-2401-11eb-81e0-67eec7a32f14.jpg)
![2](https://user-images.githubusercontent.com/40630819/98754155-073df400-2401-11eb-8b5c-0ad09ad7450a.jpg)

**Comment by devezhao** [comment]
如果要搜索 网卡IP，就要把这个字段设置为名称字段，详见 https://getrebuild.com/docs/admin/meta-entity#%E7%AE%A1%E7%90%86%E5%AE%9E%E4%BD%93

**Comment by advisen** [comment]
可以了，非常感谢，建议能在后台或者前台配置快速搜索的选项

**Comment by devezhao** [comment]
V2.1 新增了 快速查询字段 的配置，上面的文档中有提到。此文档非常重要，建议全篇阅读

**Comment by advisen** [comment]
不好意思，麻烦指导下，我在演示环境下，没找到教程文档里面关于快速查询的配置，非常感谢
![0](https://user-images.githubusercontent.com/40630819/98789177-ebf0da00-243c-11eb-9b29-6604317c1601.jpg)
![1](https://user-images.githubusercontent.com/40630819/98789185-edba9d80-243c-11eb-909c-501dd809944d.jpg)

**Comment by devezhao** [comment]
此功能尚未发布，请等待

**Comment by advisen** [comment]
好的，感谢
