### ISSUE TITLE
怎么配置环境？

### ISSUE THREAD

**Issue by Edward-Tony** [getrebuild/rebuild#258]
### 版本 / Version
TODO 2.1

### 什么问题 / What's the problem
TODO  navicat导入不了数据库文件，mysql5.5

### 如何复现此问题 / How to reproduce this problem
TODO 直接导入即可    

### 系统环境 (操作系统/MySQL版本/浏览器等) / System environment (OS/MySQL/Browser etc)
TODO 笔记本 10，5.5，navicat导入

是否可以教一下怎么配置环境，正在学习这方面的知识，碰巧遇到贵公司产品，做的很好。自己没学过，想学一学配置方面的东西

**Comment by getrebuild** [comment]
请帖一下具体错误
