### ISSUE TITLE
字段触发建议

### ISSUE THREAD

**Issue by advisen** [getrebuild/rebuild#264]
### 版本 / Version
2.1.0

### 什么问题 / What's the problem
建议在字段或者触发器里做一个触发的条件。例如，建立一个实体，引用了分类数据，在前端录入数据的时候选择不同的分类字段，显示不同的内容，如下图
![image](https://user-images.githubusercontent.com/40630819/102048352-f32f4d00-3e19-11eb-9c35-1c89a3f89832.png)
![image](https://user-images.githubusercontent.com/40630819/102048451-1fe36480-3e1a-11eb-9bae-62c3bb407558.png)

### 如何复现此问题 / How to reproduce this problem
TODO

### 系统环境 (操作系统/MySQL版本/浏览器等) / System environment (OS/MySQL/Browser etc)
TODO

**Comment by getrebuild** [comment]
可以通过数据校验实现 https://getrebuild.com/docs/admin/triggers#%E6%95%B0%E6%8D%AE%E6%A0%A1%E9%AA%8C
