### ISSUE TITLE
优化建议：实体详情页可以直接添加本实体关联动态

### ISSUE THREAD

**Issue by westudiodev** [getrebuild/rebuild#280]
### 版本 / Version
<img width="1430" alt="Screen Shot 2021-01-17 at 20 54 42" src="https://user-images.githubusercontent.com/33219803/104843605-7acf1680-5906-11eb-8b25-b4778bc46573.png">
2.2-dev
### 什么问题 / What's the problem

AS IS： 目前给一个实体增加动态信息，必须到动态模块添加，并且还要查询选择相关联的对象记录才能添加，步骤较多很不方便
TO BE：如果能够在实体详情页界面直接添加（或者提供添加按钮，弹窗形式显示关联动态发布UI）会极大改进用户体验。少很多步骤，其实很多情况下，动态比审批还要重要

### 如何复现此问题 / How to reproduce this problem
TODO

### 系统环境 (操作系统/MySQL版本/浏览器等) / System environment (OS/MySQL/Browser etc)
TODO

**Comment by getrebuild** [comment]
V2.3 已实现。在 [新建相关] 菜单下

**Comment by westudiodev** [comment]
之前我提过同样的需求建议，Rebuild团队已经采纳并在2.3版实现了。



------------------

&nbsp;
WorkLife-IT人生
     姓名：&nbsp; 海皮船长
  职务：&nbsp; 群主
 「WorkLife.icu」IT人互助社群，让打工人更轻松些


&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Fri, Apr 16, 2021 10:48 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [getrebuild/rebuild] 优化建议：实体详情页可以直接添加本实体关联动态 (#280)

&nbsp;



 
V2.3 已实现。在 [新建相关] 菜单下
