### ISSUE TITLE
导入数据时火狐浏览器崩溃

### ISSUE THREAD

**Issue by Odeandie** [getrebuild/rebuild#300]
导入数据，在选择文件之后，Forefox 会崩溃，但 Chrome 就没有问题。
Firefox 版本，78.8.0esr（64 位）
Chromr 版本，89.0.4389.82（正式版本）（64 位）

**Comment by getrebuild** [comment]
经测试未发现问题。请通过以下几点验证问题所在
1. 是否是文件本身的问题（换个文件试试）
2. 在动态中上传文件（测试上传功能是否正常）

**Comment by Odeandie** [comment]
是火狐浏览器 ESR 78.8 版本的问题
