### ISSUE TITLE
登录日志的登录时间的时区差

### ISSUE THREAD

**Issue by Odeandie** [getrebuild/rebuild#301]
在登录日志看到的时间是北京时间，在数据库（MySQL）中看到的是 8 小时之前。
查看服务器，CentOS 的时区为 Shanghai，MySQL 的时区为 CST。

**Comment by getrebuild** [comment]
https://www.cnblogs.com/gengyufei/p/11730308.html
https://www.baidu.com/s?wd=mysql%20%E6%97%B6%E5%8C%BA8%E5%B0%8F%E6%97%B6

**Comment by getrebuild** [comment]
MySQL 8 修改了时区设置，需要调整 `serverTimezone` 参数。如下
1. 找到 RB 数据目录下的 `.rebuild` 文件
2. 将 `serverTimezone=GMT` 替换为 `serverTimezone=Asia/Shanghai`（注意本例中的 `Asia/Shanghai`，请根据所在地区做调整，本例仅适用国内）
3. 保存文件并重启 RB

**Comment by Odeandie** [comment]
> MySQL 8 修改了时区设置，需要调整 `serverTimezone` 参数。如下
> 
> 1. 找到 RB 数据目录下的 `.rebuild` 文件
> 
> 2. 将 `serverTimezone=GMT` 替换为 `serverTimezone=Asia/Shanghai`（注意本例中的 `Asia/Shanghai`，请根据所在地区做调整，本例仅适用国内）
> 
> 3. 保存文件并重启 RB

已成功。
