### ISSUE TITLE
需求：实体对象也可以关联任务，类似动态

### ISSUE THREAD

**Issue by westudiodev** [getrebuild/rebuild#304]
现在任务只能关联到项目，希望实体对象也可以关联任务，类似动态

这样非常方便根据业务表单来跟踪相关任务
<img width="1428" alt="Screen Shot 2021-03-14 at 12 28 18" src="https://user-images.githubusercontent.com/33219803/111057259-0dcc9d00-84c1-11eb-9d1c-2ddf034075f1.png">

**Comment by getrebuild** [comment]
在 2.3 中任务已可以关联业务记录
