### ISSUE TITLE
图片点击空白处时也可关闭

### ISSUE THREAD

**Issue by Odeandie** [getrebuild/rebuild#310]
现在好像是只能点到右上角的“X”才能
是否会考虑空白处也能关闭图片查看？

**Comment by getrebuild** [comment]
1. 按键 `ESC` 可关闭
2. 空白处不可关闭是权衡后的结果，实际上 RB 支持此特性，只是被禁用了 https://github.com/getrebuild/rebuild/blob/master/src/main/resources/web/assets/js/file-preview.js#L17
