### ISSUE TITLE
使用admin/admin登录提供错误的用户名或密码

### ISSUE THREAD

**Issue by leonlee723** [getrebuild/rebuild#360]
### 版本 / Version
2.4.1

### 什么问题 / What's the problem
https://nightly.getrebuild.com/user/login
使用admin/admin登录提供错误的用户名或密码，rebuild/rebuild可以正常登录

### 如何复现此问题 / How to reproduce this problem
TODO

### 系统环境 (操作系统/MySQL版本/浏览器等) / System environment (OS/MySQL/Browser etc)
TODO

**Comment by getrebuild** [comment]
密码已恢复默认。
