### ISSUE TITLE
IE 浏览器访问问题

### ISSUE THREAD

**Issue by aertaa** [getrebuild/rebuild#388]
### 版本 / Version
2.5.1-release

### 什么问题 / What's the problem
任何版本 IE 浏览器访问均显示 500 错误

### 如何复现此问题 / How to reproduce this problem
使用任何版本 IE 浏览器访问 https://nightly.getrebuild.com/

### 系统环境 (操作系统/MySQL版本/浏览器等) / System environment (OS/MySQL/Browser etc)
TODO

**Comment by getrebuild** [comment]
经测试未能复现该问题，我们尝试对可能产生问题的地方进行了优化。线上 demo 现已更新，请再次访问 https://nightly.getrebuild.com/ 验证此问题

**Comment by aertaa** [comment]
已重新验证，问题得到修复，谢谢。
