### ISSUE TITLE
需求建议实体表单增加tag类型字段

### ISSUE THREAD

**Issue by westudiodev** [getrebuild/rebuild#401]
增加Tag类型
用户可以输入（从tag中选择）多个tag
可以根据tag过滤实体数据

效果图：
![image (35)](https://user-images.githubusercontent.com/33219803/140694688-bd6f101b-5506-4133-b7f1-65a23e669ec3.jpg)

**Comment by getrebuild** [comment]
纳入后续开发需求

**Comment by getrebuild** [comment]
此字段类型已在 V3.2 中支持（可能暂时不会公开发布）
