### ISSUE TITLE
需求建议：实体详情页增加相关联的文件列表tab页

### ISSUE THREAD

**Issue by westudiodev** [getrebuild/rebuild#408]
实体详情页增加文件tab页
可以显示并上传该实体相关联的文件

![image](https://user-images.githubusercontent.com/33219803/143382249-98207ed3-a53b-4dc4-8301-b53441f4b491.png)

【WorkLife-IT人互助社区】
wechat：helpin001

**Comment by getrebuild** [comment]
纳入后续开发需求

**Comment by getrebuild** [comment]
2.8 已加入
