### ISSUE TITLE
明细实体批量增加问题

### ISSUE THREAD

**Issue by aertaa** [getrebuild/rebuild#442]
### 版本 / Version
2.8.0

### 什么问题 / What's the problem
填写多个明细实体时，若明细实体含有图片字段，任意行添加的图片都被上传至第一行明细数据的图片字段。

### 如何复现此问题 / How to reproduce this problem
线上 nightly 环境 [00001主实体] 新建时，添加 N 行明细数据，任意行上传图片，图片被上传至第一行明细数据的图片字段。

### 系统环境 (操作系统/MySQL版本/浏览器等) / System environment (OS/MySQL/Browser etc)
any

**Comment by getrebuild** [comment]
感谢反馈。此问题将在近期更新发布。
