### ISSUE TITLE
实体管理支持以联合主键的形式设置“允许重复”

### ISSUE THREAD

**Issue by Odeandie** [getrebuild/rebuild#478]
### 版本 / Version
2.9.2

### 什么问题 / What's the problem
实体管理 -> 字段管理，“允许重复”这个功能支持多字段设置的联合主键

### 如何复现此问题 / How to reproduce this problem
Null

### 系统环境 (操作系统/MySQL版本/浏览器等) / System environment (OS/MySQL/Browser etc)
Null

**Comment by getrebuild** [comment]
此问题已在 V3.4 中优化，支持按“或”与“和”的关键检查重复。
