### ISSUE TITLE
高级查询更改“且或”关系时的问题

### ISSUE THREAD

**Issue by Odeandie** [getrebuild/rebuild#483]
2.9.3
高级查询条件中，在或、且、表达式做更换时
需要点击 2 下，才会有选中状态

**Comment by getrebuild** [comment]
高级查询组件应用在系统的多个地方，目前已知在图表设计的时候有此问题，其他地方暂未发现。请指出具体位置。

**Comment by Odeandie** [comment]
自定义的实体里保存了查询条件
在这儿生成了一个高级查询

对这个高级查询进行修改的时候
遇到的这个问题，可复现

**Comment by getrebuild** [comment]
此问题将在 2.9.4 中修复，感谢反馈！
