### ISSUE TITLE
数据库密码的更改

### ISSUE THREAD

**Issue by Odeandie** [getrebuild/rebuild#485]
当数据库密码存在特殊字符时
会导致 mysqldump 的备份失败
如提示“找不到命令”
经测试，定位到我生成的随机密码中包括“+”
现在想修改数据库密码
可在配置中，找不到相应入口
要更改数据目录下的 .rebuild 文件的话
还需要 AES 的密码加密才可以……

怎样才能改这个密码呢？

**Comment by Odeandie** [comment]
/bin/sh: **+n8EA0FQ2Uw[U**: 未找到命令 mysqldump: [Warning] Using a password on the command line interface can be insecure.
Usage: mysqldump [OPTIONS] database [tables] OR mysqldump [OPTIONS] --databases [OPTIONS] DB1 [DB2 DB3...] OR mysqldump [OPTIONS] --all-databases [OPTIONS]
For more options, use mysqldump --help

**+n8EA0FQ2Uw[U**就是我数据库密码中的一部分……

**Comment by Odeandie** [comment]
嗨 问题看起来还是没有解决呢![image](https://user-images.githubusercontent.com/35424746/179688057-cd6fca3c-8377-4936-8c6a-64db55395e99.jpeg)

**Comment by getrebuild** [comment]
因代码合并问题导致 2.9.4 中并未包含此问题的修复，此问题延迟到 2.9.5 中修复。
