### ISSUE TITLE
高级查询中缺少等于不等于

### ISSUE THREAD

**Issue by Odeandie** [getrebuild/rebuild#489]
当字段类型为“分类”时
条件仅有包含、不包含
把字段改为”引用”后
条件中才出现等于、不等于

这个是漏掉的，还是考虑后不做的呢？

**Comment by getrebuild** [comment]
包含/不包含可以当做等于/不等于使用。

**Comment by Odeandie** [comment]
> 包含/不包含可以当做等于/不等于使用。

当要查询的条件是“通过”或“不通过”的情况
搜“通过”，也出现“不通过”
因为包含了 (･_･;

**Comment by getrebuild** [comment]
> > 包含/不包含可以当做等于/不等于使用。
> 
> 当要查询的条件是“通过”或“不通过”的情况 搜“通过”，也出现“不通过” 因为包含了 (･_･;

确实会有此问题，我们会考虑后续版本中优化此功能。感谢你的反馈！

**Comment by getrebuild** [comment]
3.0 中已优化。
