### ISSUE TITLE
触发器源实体的字段选择没有位置记忆功能

### ISSUE THREAD

**Issue by Odeandie** [getrebuild/rebuild#491]
2.9.5 配置触发器时遇到
目标实体的字段会有位置记忆
但源实体的字段每次都是从头展开
有一点点的不便利（基于目标实体可实现的背景下
![image](https://user-images.githubusercontent.com/35424746/180493114-19355aa8-3052-4a29-9030-84deda35709d.png)

**Comment by getrebuild** [comment]
感谢反馈！我们将在后续版本中考虑优化。
