### ISSUE TITLE
增加钉钉机器人通知

### ISSUE THREAD

**Issue by wangweipeng1314** [getrebuild/rebuild#503]
钉钉集成里加入钉钉机器人通知，把通知发送到群里

**Comment by getrebuild** [comment]
词功能将考虑在后续版本中提供。

**Comment by getrebuild** [comment]
https://open.dingtalk.com/document/orgapp/send-group-helper-message

**Comment by getrebuild** [comment]
V3.4 版本已提供钉钉机器人、企微机器人通知。见文档 https://getrebuild.com/docs/admin/trigger/sendnotification
