### ISSUE TITLE
仪表盘的排序问题

### ISSUE THREAD

**Issue by Odeandie** [getrebuild/rebuild#504]
2.9.5，已经指定纬度中的日期降序后
再指定数值降序时，会出现下面错乱的问题
![image](https://user-images.githubusercontent.com/35424746/182543959-804ffeb9-beb9-4bf4-84da-d35d4fe1416d.png)

**Comment by getrebuild** [comment]
感谢反馈，此问题将在下一版本修复。

**Comment by Odeandie** [comment]
问题在 3.0.2 中，以新的形式复现了

![image](https://user-images.githubusercontent.com/35424746/189046405-0ea6c7fd-f2b2-4083-9109-e9a563c8950d.png)
