### ISSUE TITLE
字段字体太小了，用发票打印机打印出来很小，很模糊

### ISSUE THREAD

**Issue by wangweipeng1314** [getrebuild/rebuild#505]
支持调整字段字体大小的话，打印出来会比较清晰，或者支持打印表单的单独设计排版
![微信图片_20220805104727](https://user-images.githubusercontent.com/79432074/182991024-c050431b-5f76-4759-81d1-6ff454fb0d34.jpg)

**Comment by getrebuild** [comment]
感谢反馈，我们将考虑在后续版本中提供支持。

**Comment by getrebuild** [comment]
3.0 已提供字体大小选项。

![WPJHM)S~ 5E2RY@ WIPL%{5](https://user-images.githubusercontent.com/42044143/184163416-3d49ba2d-7d83-4edc-87e4-be568ad1fbc9.png)

**Comment by wangweipeng1314** [comment]
已更新使用，非常方便，感谢

**Comment by pgy866** [comment]
https://toscode.gitee.com/CcSimple/vue-plugin-hiprint
Demo预览：https://ccsimple.gitee.io/vue-plugin-hiprint/

可以这样自由设计打印模板吗

**Comment by wangweipeng1314** [comment]
这种就可以&nbsp;


流星划过天堂
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月27日(星期二) 晚上9:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [getrebuild/rebuild] 字段字体太小了，用发票打印机打印出来很小，很模糊 (Issue #505)





 
https://toscode.gitee.com/CcSimple/vue-plugin-hiprint
 Demo预览：https://ccsimple.gitee.io/vue-plugin-hiprint/
 
可以这样自由设计打印模板吗

**Comment by getrebuild** [comment]
> https://toscode.gitee.com/CcSimple/vue-plugin-hiprint Demo预览：https://ccsimple.gitee.io/vue-plugin-hiprint/
> 
> 可以这样自由设计打印模板吗

可以使用 Excel 报表模板设计，https://getrebuild.com/docs/admin/excel-admin
