### ISSUE TITLE
旧实体无法拉入新的父级菜单

### ISSUE THREAD

**Issue by wangweipeng1314** [getrebuild/rebuild#511]
![1111111111](https://user-images.githubusercontent.com/79432074/184296999-92a2fd6d-06fa-43e7-8e7b-01d96b9967b4.JPG)
导航菜单里，之前的菜单不能拉入新建的父级菜单，如果后续新建的实体过多，就不方便与之前的实体收纳到一起。这样会导致后续的实体都是直接展开的，不方便使用

**Comment by getrebuild** [comment]
感谢反馈，我们将在后续考虑加入此功能。
