### ISSUE TITLE
仪表盘的排序问题2

### ISSUE THREAD

**Issue by Odeandie** [getrebuild/rebuild#521]
### 版本 / Version
3.0.2

### 什么问题 / What's the problem
仪表盘的排序问题，https://github.com/getrebuild/rebuild/issues/504#issue-1326766443

### 如何复现此问题 / How to reproduce this problem
指定 2 个排序的逻辑

### 系统环境 (操作系统/MySQL版本/浏览器等) / System environment (OS/MySQL/Browser etc)
CentOS 7

![image](https://user-images.githubusercontent.com/35424746/189046405-0ea6c7fd-f2b2-4083-9109-e9a563c8950d.png)

**Comment by getrebuild** [comment]
感谢反馈，此功能目前暂无优化方案，建议避免多字段排序使用。
