### ISSUE TITLE
使用Smtp邮件信息发送邮件，中文发送者乱码????

### ISSUE THREAD

**Issue by LLBlood** [getrebuild/rebuild#570]
### 版本 / Version
rebuild 3.1.3

### 什么问题 / What's the problem
使用Smtp配置邮件信息，如果邮件发送人为中文信息，则接收邮件会显示????
![image](https://user-images.githubusercontent.com/51195412/216005609-45b9e06c-3a00-46b1-ba53-c7b00448b991.png)

### 如何复现此问题 / How to reproduce this problem
进入rebuild登录页面，选择立即注册账号，输入邮箱信息，点击获取验证码

### 系统环境 (操作系统/MySQL版本/浏览器等) / System environment (OS/MySQL/Browser etc)
Centos7

**Comment by getrebuild** [comment]
感谢反馈。经验证此问题不存在，请检查服务器操作系统相关编码配置。
