### ISSUE TITLE
feat: [项目模块] 支持以表格显示任务模式

### ISSUE THREAD

**Issue by goodclub** [getrebuild/rebuild#612]
<img width="966" alt="Screenshot 2023-05-08 at 15 56 28" src="https://user-images.githubusercontent.com/59728604/236768482-4175716e-d92f-49a5-896b-5cdbb42f1752.png">

**Comment by getrebuild** [comment]
感谢建议。我们将在后续版本考虑增加此功能。

**Comment by westudiodev** [comment]
技术实现上也可以直接复用实体模块的表格就好，把task实体UI显示出来就OK了
&nbsp;
&nbsp;
------------------&nbsp;原始邮件&nbsp;------------------
发件人: "REBUILD&nbsp;企业管理系统"; 
发送时间: 2023年5月8日(星期一) 下午4:03
收件人: "getrebuild/rebuild"; 
抄送: "Subscribed"; 
主题: Re: [getrebuild/rebuild] feat: [项目模块] 支持以表格显示任务模式 (Issue #612)

&nbsp;



 
感谢建议。我们将在后续版本考虑增加此功能。
 
&mdash;
