### ISSUE TITLE
记录转换的目标实体中包含内部标识为“length”的字段时记录转换页面加载异常

### ISSUE THREAD

**Issue by zhao-hw** [getrebuild/rebuild#631]
### 版本 / Version
3.3.3

### 什么问题 / What's the problem
记录转换的目标实体中包含内部标识为“length”的字段时记录转换页面加载异常

### 如何复现此问题 / How to reproduce this problem
任意实体中新增字段，内部标识为“length”
新建记录转换，目标实体选择上一步中新建的实体

参考演示项目中的记录转换037-0188faf7fa212f5a
![image](https://github.com/getrebuild/rebuild/assets/32899357/1f120d4c-55b7-4e9b-b803-61ab4bc04c7f)

### 系统环境 (操作系统/MySQL版本/浏览器等) / System environment (OS/MySQL/Browser etc)
TODO

**Comment by getrebuild** [comment]
感谢反馈，问题已确认，会在后续修订版发布修复。
