### ISSUE TITLE
配置记录转换时如果设置的所有字段映射都是固定值，会转换失败

### ISSUE THREAD

**Issue by zhao-hw** [getrebuild/rebuild#633]
### 版本 / Version
3.3.3

### 什么问题 / What's the problem
配置记录转换时如果设置的所有字段映射都是固定值，会转换失败
非预览模式
![image](https://github.com/getrebuild/rebuild/assets/32899357/e1f8b509-816c-406d-86cd-7b848d307128)
预览模式
![image](https://github.com/getrebuild/rebuild/assets/32899357/09073e8e-053c-4445-8903-35cb2e907199)

### 如何复现此问题 / How to reproduce this problem
新建任意实体转换到任意实体的记录转换
只设置一个固定值的字段映射
使用详情页面的“准换为”功能，选择新建的记录转换

参考演示项目中的记录转换037-018914bd3cc25372
![image](https://github.com/getrebuild/rebuild/assets/32899357/bdaf75b5-f65f-4bb9-815a-4e2cbd6c45a6)

### 系统环境 (操作系统/MySQL版本/浏览器等) / System environment (OS/MySQL/Browser etc)
TODO

**Comment by getrebuild** [comment]
感谢反馈，V3.3.4 已修复。

**Comment by getrebuild** [comment]
感谢反馈，问题已修复将在后续版本中发布。

**Comment by getrebuild** [comment]
此问题已在 V3.4 中修复，近期发布。
