### ISSUE TITLE
货币格式小数导致预览模式记录转换表单保存失败

### ISSUE THREAD

**Issue by zhao-hw** [getrebuild/rebuild#638]
### 版本 / Version
3.3.4

### 什么问题 / What's the problem
预览模式的记录转换的表单提交时货币格式的字段的值会带有货币符号导致提交失败

### 如何复现此问题 / How to reproduce this problem
创建一个记录转换，配置一个货币格式小数到小数的映射，并打开预览模式
在源实体详情页使用转化为功能，选择上一步创建的记录转换
保存表单，系统报错

正常表单提交
![image](https://github.com/getrebuild/rebuild/assets/32899357/11c4facb-7076-4e4d-8131-f53b5432ef89)
记录转换预览模式表单提交
![image](https://github.com/getrebuild/rebuild/assets/32899357/bf50d9d3-ee5b-4640-aa33-62c48334cf3a)
参考演示项目中的记录转换037-018947bb63b30668

### 系统环境 (操作系统/MySQL版本/浏览器等) / System environment (OS/MySQL/Browser etc)
TODO

**Comment by zhao-hw** [comment]
参考演示项目中的记录转换037-018947bb63b30668

**Comment by getrebuild** [comment]
感谢反馈，问题已修复将在后续版本中发布。

**Comment by getrebuild** [comment]
此问题已在 V3.4 中修复，近期发布。
