### ISSUE TITLE
frontjs中视图打开函数不生效

### ISSUE THREAD

**Issue by zhao-hw** [getrebuild/rebuild#647]
### 版本 / Version
3.4.0-beta1

### 什么问题 / What's the problem
frontjs中视图打开函数不生效

### 如何复现此问题 / How to reproduce this problem
参考演示项目中的出库实体
![image](https://github.com/getrebuild/rebuild/assets/32899357/bd9c3227-ae66-4354-b1ae-0f85a60f4c84)
![image](https://github.com/getrebuild/rebuild/assets/32899357/ad858a61-a3f3-487e-9f45-01763b80bc50)

### 系统环境 (操作系统/MySQL版本/浏览器等) / System environment (OS/MySQL/Browser etc)
TODO

**Comment by getrebuild** [comment]
视图为 iframe 因此不与列表同一 URL，其地址如 `/app/OutStock/view/xxxx`。可将匹配地址 `/app/OutStock/list` 改为 `/app/OutStock/` 即可。
