### ISSUE TITLE
请问下我上传的文件怎么不显示呢？

### ISSUE THREAD

**Issue by zhoulincome** [getrebuild/rebuild#649]
### 版本 / Version
3.3.4   直接下载zip包后进行sh脚本启动

### 什么问题 / What's the problem
在导航栏的文件功能中创建目录，创建好后上传文件，文件上传成功了，但是服务器的列表为啥没有显示呢？

### 如何复现此问题 / How to reproduce this problem
![image](https://github.com/getrebuild/rebuild/assets/6369667/096db5bf-4d9d-437d-a9a5-a0fe1cb1d023)

![image](https://github.com/getrebuild/rebuild/assets/6369667/656ec448-7eb8-418b-a928-e14fd3459d83)
后台文件：
![image](https://github.com/getrebuild/rebuild/assets/6369667/3156b792-9223-48b6-9677-08ef1913793e)

### 系统环境 (操作系统/MySQL版本/浏览器等) / System environment (OS/MySQL/Browser etc)
mysql 5.7.42

**Comment by getrebuild** [comment]
感谢反馈。经测试未能复现此问题，且未有其他用户反馈过类似情况。

建议尝试方式：
1. 确认是否有 WAF 阻止了文件保存请求
2. 打开浏览器 F12 并观察“网络”和“控制台”选项卡观察保存请求是否有异常情况

**Comment by zhoulincome** [comment]
经查看文件已经保存在服务器，只是接口调用少了。
正常情况：
![image](https://github.com/getrebuild/rebuild/assets/6369667/cca2879c-bc00-4ff0-a5d3-a0c6dd404d2c)
非正常情况：
![image](https://github.com/getrebuild/rebuild/assets/6369667/ebfc3843-19e5-4e7c-892b-d6bd02c77269)
发现：
http://crm.tfgc.com/files/post-files?folder=024-018a1c6d928a000d和

http://crm.tfgc.com/files/list-file?entry=024-018a1c6d928a000d&sort=&q=&pageNo=1&pageSize=40&_=1692774824103
未调用。
关键接口未发现报错
![image](https://github.com/getrebuild/rebuild/assets/6369667/03ca8c8d-1835-48a0-895b-4ecde76e0978)

**Comment by zhoulincome** [comment]
这个保存针对小文件直接就成功了，但是文件大概10多M的时候发现不调用后面两个接口，关键是还不报错西信息，让人莫名的奇怪

**Comment by getrebuild** [comment]
可观察 `post-files` 调用是否异常。

**Comment by zhoulincome** [comment]
经查看post-files这个接口在异常的时候未发送请求！！所以就很纳闷
正常情况：
请求：
http://crm.tfgc.com/filex/upload?temp=false&amp;noname=false
返回数据：
{
&nbsp; &nbsp; "data": "rb/20230823/151410837__西藏高驰科技信息产业集团有限责任公司岗位职责梳理【0811】.pdf",
&nbsp; &nbsp; "error_code": 0,
&nbsp; &nbsp; "error_msg": "调用成功"
}



我把非正常接口返回的参数发给你：
http://crm.tfgc.com/filex/upload?temp=false&amp;noname=false
返回数据：
{
&nbsp; &nbsp; "data": "rb/20230823/151451467__03详细设计说明书-副本.pdf",
&nbsp; &nbsp; "error_code": 0,
&nbsp; &nbsp; "error_msg": "调用成功"
}

服务器存储地址：



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "getrebuild/rebuild"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月23日(星期三) 下午3:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [getrebuild/rebuild] 请问下我上传的文件怎么不显示呢？ (Issue #649)





 
可观察 post-files 调用是否异常。

**Comment by getrebuild** [comment]
`post-files` 会在点击 [上传] 按钮时调用。如未点击、或点击后未调用、或调用出错，那么这个就是问题所在。

![SI$LQ$A82HD2%BOQ5IXIE0M](https://github.com/getrebuild/rebuild/assets/42044143/14be0298-aaaf-40eb-91ca-5f1474646abd)

**Comment by zhoulincome** [comment]
我理解了，我大概晓得啥原因：
1、当图片很大时，你们的那个上传文件接口：upload?temp=false&amp;noname=false，未及时响应，也没有类似loading
2、当上传还未上传完成时，我点了上传按钮，是不是你们会判断为空就不会发post-file接口？


建议：你们在上传文件这块做一个优化。如果文件正在上传点击上传的时候给一个等待。还有就是那个弹框最好暂时不关闭。






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "getrebuild/rebuild"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月23日(星期三) 下午3:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [getrebuild/rebuild] 请问下我上传的文件怎么不显示呢？ (Issue #649)





 
post-files 会在点击 [上传] 按钮时调用。如未点击、或点击后未调用、或调用出错，那么这个就是问题所在。

**Comment by getrebuild** [comment]
感谢建议，后续版本会考虑优化。
