### ISSUE TITLE
提交数据运行时间长，有时超过十秒

### ISSUE THREAD

**Issue by flyinsz** [getrebuild/rebuild#690]
### 版本 / Version
3.4.6

### 什么问题 / What's the problem
提交数据运行时间长，有时超过十秒

### 如何复现此问题 / How to reproduce this problem
详见log
[log.txt](https://github.com/getrebuild/rebuild/files/13608652/log.txt)

### 系统环境 (操作系统/MySQL版本/浏览器等) / System environment (OS/MySQL/Browser etc)
Centos7.9
[log.txt](https://github.com/getrebuild/rebuild/files/13608659/log.txt)

**Comment by getrebuild** [comment]
请补充相关触发器配置截图。

**Comment by flyinsz** [comment]
> 请补充相关触发器配置截图。

![image](https://github.com/getrebuild/rebuild/assets/27534375/fd9c3cb6-ffe2-4d95-8031-9393c2265d6e)

**Comment by getrebuild** [comment]
订单触发器过多，因此需要更多的执行时间属于正常现象。观察到“分组聚合”多为报表，可启用定期执行，不影响用户操作。

**Comment by flyinsz** [comment]
> 订单触发器过多，因此需要更多的执行时间属于正常现象。观察到“分组聚合”多为报表，可启用定期执行，不影响用户操作。

定期执行是收费功能😭
