### ISSUE TITLE
功能建议：建议将触发器的立即执行按钮放到更方便的位置

### ISSUE THREAD

**Issue by love90618** [getrebuild/rebuild#701]
建议将触发器的立即执行按钮放到更方便的位置
就比如实体如下位置：
![image](https://github.com/getrebuild/rebuild/assets/13093523/1172c412-34b6-4da4-b085-6b9135429b6c)
这样更加方便快速更新实体中的数据

**Comment by getrebuild** [comment]
感谢建议，该功能设计为遗留数据执行。你可以考虑使用定期执行。
