### ISSUE TITLE
增加打印模板设计直接打印，而不是导出或者预览文件

### ISSUE THREAD

**Issue by yaoyingkeji** [getrebuild/rebuild#714]
### 版本 / Version
TODO：3.5.6

### 什么问题 / What's the problem
TODO：增加打印模板设计直接打印，而不是导出或者预览文件

### 如何复现此问题 / How to reproduce this problem
TODO：

### 系统环境 (操作系统/MySQL版本/浏览器等) / System environment (OS/MySQL/Browser etc)
TODO：deepin linux

**Comment by getrebuild** [comment]
模板可开启 PDF 导出格式，导出后会直接在浏览器中打开PDF，可供直接打印。参考 https://getrebuild.com/docs/admin/excel-admin#%E6%8A%A5%E8%A1%A8%E5%AF%BC%E5%87%BA%E6%A0%BC%E5%BC%8F
