### ISSUE TITLE
入库增加入库单价-入库单其它费用-退货红充-财务报表

### ISSUE THREAD

**Issue by yaoyingkeji** [getrebuild/rebuild#716]
### 版本 / Version
TODO

### 什么问题 / What's the problem
TODO：入库增加入库单价-入库其它费用-退货红充-等等

### 如何复现此问题 / How to reproduce this problem
TODO：

### 系统环境 (操作系统/MySQL版本/浏览器等) / System environment (OS/MySQL/Browser etc)
TODO deepin  linux

**Comment by getrebuild** [comment]
RB模板中的功能模块均为配置得出，请根据自身需要自行添加/调整即可。
