### ISSUE TITLE
触发器执行失败 : Could not compare <String, > with <JavaType, rukushuliang, 0, java.math.BigDecimal> (退货入库状态更新)

### ISSUE THREAD

**Issue by flyinsz** [getrebuild/rebuild#779]
### 版本 / Version
3.7.1

### 什么问题 / What's the problem
保存表单发生错误：触发器执行失败 : Could not compare <String, > with <JavaType, rukushuliang, 0, java.math.BigDecimal> (退货入库状态更新)

### 如何复现此问题 / How to reproduce this problem
之前3.5.6版没有问题，升级到3.7.1后出现问题

### 系统环境 (操作系统/MySQL版本/浏览器等) / System environment (OS/MySQL/Browser etc)
Linux 22.04
![屏幕截图_8-7-2024_163935_localhost](https://github.com/getrebuild/rebuild/assets/27534375/59405c74-9dfe-490b-9c7b-b85011576491)
![屏幕截图_8-7-2024_163848_localhost](https://github.com/getrebuild/rebuild/assets/27534375/88d38d65-d899-43b8-8720-1b3e67af4b75)
![屏幕截图_8-7-2024_16388_getrebuild com](https://github.com/getrebuild/rebuild/assets/27534375/06aa4267-2b28-4630-ae85-44625ca7ef08)

**Comment by getrebuild** [comment]
数字字段不可使用字符串判断，判空可使用 ISNULL 函数。
推荐阅读：https://getrebuild.com/docs/admin/trigger/fieldwriteback#%E5%AD%97%E6%AE%B5%E5%8F%98%E9%87%8F%E5%80%BC%E8%AF%B4%E6%98%8E
